apiVersion: v1
kind: Service
metadata:
  name: ada-challenge-postgres
  labels:
    app: ada-challenge
spec:
  ports:
    - port: 5432
  selector:
    app: ada-challenge
    tier: postgres
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ada-challenge-postgres-pv-claim
  labels:
    app: ada-challenge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ada-challenge-postgres
  labels:
    app: ada-challenge
spec:
  selector:
    matchLabels:
      app: ada-challenge
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ada-challenge
        tier: postgres
    spec:
      containers:
      - image: postgres:11.2
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pass
              key: password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgres
        readinessProbe:
          exec:
            command: ["psql", "-w", "-U", "postgres", "-c", "SELECT 1;"]
          initialDelaySeconds: 2
          timeoutSeconds: 1
          periodSeconds: 2
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: ada-challenge-postgres-pv-claim

